### ISSUE TITLE
어떤 자바스크립트 코딩 스타일을 적용할까요?

### ISSUE THREAD

**Issue by dimsssss** [dimsssss/cloneAlice-back#1]
저희가 결정한 javascript style(airbnb)이 es6문법인데 nodejs는 commonjs네요.

commonjs에서는 module syntax가 달라서 import,export 같은 키워드가 적용이 안되는데 

airbnb에서는 권장사항이라서 backend에 적용할 수 없습니다.

따라서 eslint 설정에서 특정 룰을 제외할 수 있는지 찾아봐야겠습니다.

만약 안될 때 어떤 style guide를 적용할까요?

**Comment by foranything** [comment]
aslant 파일에 다음과 같이

``` yml
env:
  commonjs: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
```

`commonjs`와 `airbnb-base`를 사용하게 하면 require를 사용해도 문제 없는것으로 보입니다.

이렇게 설정 하는건 어떨까요?
